[build]
  publish = "/"
  command = "mkdir -p backend/cache"

[functions]
  directory = "backend"
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.10"
  CACHE_DIR = "/tmp/cache"

[[redirects]]
  from = "/calendar"
  to = "/.netlify/functions/api_handler"
  status = 200
  query = { path = "calendar" }

[[redirects]]
  from = "/next-race"
  to = "/.netlify/functions/api_handler"
  status = 200
  query = { path = "next-race" }

[[redirects]]
  from = "/race/*"
  to = "/.netlify/functions/api_handler"
  status = 200
  query = { path = "race/:splat" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 